---
  output:
    html_document:
      mathjax: null
---
<style>
.main-container {
    max-width: 90%
}
</style>

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE
)

ggplotly_full <- function(p) {
  ggplotly(p, width = 1600, height = 800)
}
```

# Partial F-at-age Quality Control Plots {.tabset}

## Fishing Category fleets {.tabset}

### Proportion caught (number) {.tabset}

```{r, echo = FALSE, results = "asis"}
res <- lapply(stocks, function(x) {
  knitr::knit_child(text = c(
    '',
    '#### `r x`',
    '',
    '```{r}',
    'ggplotly_full(prop_yfa[[x]])',
    '```',
    ''
  ), envir = environment(), quiet = TRUE)
})
cat(unlist(res), sep = '\n')
```

### Partial F at age {.tabset}

```{r, echo = FALSE, results = "asis"}
res <- lapply(stocks, function(x) {
  knitr::knit_child(text = c(
    '',
    '#### `r x`',
    '',
    '```{r}',
    'ggplotly_full(pfatage_ayf[[x]])',
    '```',
    ''
  ), envir = environment(), quiet = TRUE)
})
cat(unlist(res), sep = '\n')
```
